Day76/first_crm/crm/urls.py
from django.conf.urls import url
from crm.views import auth,consultant,teacher

urlpatterns = [
    # 登录，注册，注销，主页
    url(r'^login/$', auth.login, name='login'),
    url(r'^reg/$', auth.reg, name='reg'),
    url(r'^index/$', auth.index, name='index'),
    url(r'^logout/$', auth.logout, name='logout'),

    # 客户管理
    url(r'^customer_list/$', consultant.customer_list, name='my_customer'),
    url(r'^public_customer_list/$', consultant.customer_list, name='public_customer'),
    url(r'^add_customer/$', consultant.oper_customer, name='add_customer'),
    url(r'^edit_customer/(\d+)/$', consultant.oper_customer, name='edit_customer'),
    url(r'^details/(\d+)/(\w+)/(\w+)/$', consultant.details, name='details'),
    url(r'^customer_change/$', consultant.customer_change, name='change'),

    # 跟进管理
    url(r'^consult_record_list/$', consultant.consult_record_list, name='consult_record'),
    url(r'^cus_consult_record_list/(\d+)/$', consultant.consult_record_list, name='cus_consult_record'),
    url(r'^add_consult_record/(?P<customer_pk>\d+)/$', consultant.oper_consult_record, name='add_consult_record'),
    url(r'^edit_consult_record/(\d+)/$', consultant.oper_consult_record, name='edit_consult_record'),

    # 报名管理
    url(r'^enrollment_list/$', consultant.enrollment_list, name='enrollment'),
    url(r'^add_enrollment/(?P<customer_pk>\d+)/$', consultant.oper_enrollment, name='add_enrollment'),
    url(r'^edit_enrollment/(\d+)/$', consultant.oper_enrollment, name='edit_enrollment'),

    # 班级管理
    url(r'^class_list/$', teacher.class_list, name='class'),
    url(r'^add_class/$', teacher.OperClass.as_view(), name='add_class'),
    url(r'^edit_class/(\d+)/$', teacher.OperClass.as_view(), name='edit_class'),

    #课程记录管理
    url(r'^course_record_list/(\d+)/$', teacher.course_record_list, name='course_record'),
    url(r'^add_course_record/(?P<class_pk>\d+)/$', teacher.oper_course_record, name='add_course_record'),
    url(r'^edit_course_record/(\d+)/$', teacher.oper_course_record, name='edit_course_record'),

    #学习记录管理
    url(r'^add_study_record/$', teacher.add_study_record, name='add_study_record'),
    url(r'^study_record_list/(\d+)/$', teacher.study_record_list, name='study_record_list'),

]

Day76/first_crm/first_crm/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^crm/', include('crm.urls')),
    url(r'^rbac/', include('permission.urls')),
]

Day76/first_crm/crm/models.py
from django.db import models
from multiselectfield import MultiSelectField
from django.utils.safestring import mark_safe
from permission.models import User

course_choices = (('Linux', 'Linux中高级'),
                  ('PythonFullStack', 'Python高级全栈开发'),)

class_type_choices = (('fulltime', '脱产班',),
                      ('online', '网络班'),
                      ('weekend', '周末班',),)

source_type = (('qq', "qq群"),
               ('referral', "内部转介绍"),
               ('website', "官方网站"),
               ('baidu_ads', "百度推广"),
               ('office_direct', "直接上门"),
               ('WoM', "口碑"),
               ('public_class', "公开课"),
               ('website_luffy', "路飞官网"),
               ('others', "其它"),)

enroll_status_choices = (('signed', "已报名"),
                         ('unregistered', "未报名"),
                         ('studying', '学习中'),
                         ('paid_in_full', "学费已交齐"))

seek_status_choices = (('A', '近期无报名计划'), ('B', '1个月内报名'), ('C', '2周内报名'), ('D', '1周内报名'),
                       ('E', '定金'), ('F', '到班'), ('G', '全款'), ('H', '无效'),)
pay_type_choices = (('deposit', "订金/报名费"),
                    ('tuition', "学费"),
                    ('transfer', "转班"),
                    ('dropout', "退学"),
                    ('refund', "退款"),)

attendance_choices = (('checked', "已签到"),
                      ('vacate', "请假"),
                      ('late', "迟到"),
                      ('absence', "缺勤"),
                      ('leave_early', "早退"),)

score_choices = ((100, 'A+'),
                 (90, 'A'),
                 (85, 'B+'),
                 (80, 'B'),
                 (70, 'B-'),
                 (60, 'C+'),
                 (50, 'C'),
                 (40, 'C-'),
                 (0, ' D'),
                 (-1, 'N/A'),
                 (-100, 'COPY'),
                 (-1000, 'FAIL'),)


class Department(models.Model):
    """
    部门表
    """
    name = models.CharField(max_length=32, verbose_name="部门名称")
    count = models.IntegerField(verbose_name="人数", default=0)

    def __str__(self):
        return self.name


class UserProfile(User):
    """
    用户表
    """
    username = models.EmailField(max_length=255, unique=True, )
    password = models.CharField(max_length=128)
    name = models.CharField('名字', max_length=32)
    department = models.ForeignKey('Department', default=None, blank=True, null=True)
    mobile = models.CharField('手机', max_length=32, default=None, blank=True, null=True)
    memo = models.TextField('备注', blank=True, null=True, default=None)
    date_joined = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Customer(models.Model):
    """
    客户表
    """
    qq = models.CharField('QQ', max_length=64, unique=True, help_text='QQ号必须唯一')
    qq_name = models.CharField('QQ昵称', max_length=64, blank=True, null=True)
    name = models.CharField('姓名', max_length=32, blank=True, null=True, help_text='学员报名后，请改为真实姓名')
    sex_type = (('male', '男'), ('female', '女'))
    sex = models.CharField("性别", choices=sex_type, max_length=16, default='male', blank=True, null=True)
    birthday = models.DateField('出生日期', default=None, help_text="格式yyyy-mm-dd", blank=True, null=True)
    phone = models.BigIntegerField('手机号', blank=True, null=True)
    source = models.CharField('客户来源', max_length=64, choices=source_type, default='qq')
    introduce_from = models.ForeignKey('self', verbose_name="转介绍自学员", blank=True, null=True)
    course = MultiSelectField("咨询课程", choices=course_choices)
    class_type = models.CharField("班级类型", max_length=64, choices=class_type_choices, default='fulltime')
    status = models.CharField("状态", choices=enroll_status_choices, max_length=64, default="unregistered",
                              help_text="选择客户此时的状态")
    last_consult_date = models.DateField("最后跟进日期", auto_now_add=True)
    next_date = models.DateField("预计再次跟进时间", blank=True, null=True)
    consultant = models.ForeignKey('UserProfile', verbose_name="销售", related_name='customers', blank=True, null=True, )
    class_list = models.ManyToManyField('ClassList', verbose_name="已报班级", blank=True)
    customer_note = models.TextField("客户备注", blank=True, null=True, )

    def get_status(self):
        dic = {
            'signed': "blue",
            'unregistered': "gray",
            'studying': 'green',
            'paid_in_full': "red"
        }
        return mark_safe(
            '<span style="color:white; background-color:{};padding: 5px; border-radius: 8%">{}</span>'.format(
                dic.get(self.status), self.get_status_display()))

    def __str__(self):
        ret = self.name
        if ret:
            return ret
        return self.qq


class Campus(models.Model):
    """
    校区表
    """
    name = models.CharField(verbose_name='校区', max_length=64)
    address = models.CharField(verbose_name='详细地址', max_length=512, blank=True, null=True)

    def __str__(self):
        return self.name


class ClassList(models.Model):
    """
    班级表
    """
    course = models.CharField("课程名称", max_length=64, choices=course_choices)
    semester = models.IntegerField("学期")
    campuses = models.ForeignKey('Campus', verbose_name="校区")
    price = models.IntegerField("学费", default=10000)
    memo = models.CharField('说明', blank=True, null=True, max_length=100)
    start_date = models.DateField("开班日期")
    graduate_date = models.DateField("结业日期", blank=True, null=True)
    teachers = models.ManyToManyField('UserProfile', verbose_name="老师",blank=True)
    class_type = models.CharField(choices=class_type_choices, max_length=64, verbose_name='班级类型', blank=True,
                                  null=True)

    class Meta:
        unique_together = ("course", "semester", 'campuses')

    def __str__(self):
        return '{}-{}'.format(self.get_course_display(), self.semester)


class ConsultRecord(models.Model):
    """
    跟进记录表
    """
    customer = models.ForeignKey('Customer', verbose_name="所咨询客户")
    status = models.CharField("跟进状态", max_length=8, choices=seek_status_choices, help_text="选择客户此时的状态")
    consultant = models.ForeignKey("UserProfile", verbose_name="跟进人", related_name='records')
    date = models.DateTimeField("跟进日期", auto_now_add=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)
    note = models.TextField(verbose_name="跟进内容...")


class Enrollment(models.Model):
    """
    报名表
    """

    customer = models.ForeignKey('Customer', verbose_name='客户名称')
    school = models.ForeignKey('Campus')
    enrolment_class = models.ForeignKey("ClassList", verbose_name="所报班级")
    why_us = models.TextField("为什么报名", max_length=1024, default=None, blank=True, null=True)
    your_expectation = models.TextField("学完想达到的具体期望", max_length=1024, blank=True, null=True)
    contract_agreed = models.BooleanField("我已认真阅读完培训协议并同意全部协议内容", default=False)
    contract_approved = models.BooleanField("审批通过", help_text="在审阅完学员的资料无误后勾选此项,合同即生效", default=False)
    enrolled_date = models.DateTimeField(auto_now_add=True, verbose_name="报名日期")
    memo = models.TextField('备注', blank=True, null=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)

    class Meta:
        unique_together = ('enrolment_class', 'customer')


class PaymentRecord(models.Model):
    """
    缴费记录表
    """
    pay_type = models.CharField("费用类型", choices=pay_type_choices, max_length=64, default="deposit")
    paid_fee = models.IntegerField("费用数额", default=0)
    note = models.TextField("备注", blank=True, null=True)
    date = models.DateTimeField("交款日期", auto_now_add=True)
    course = models.CharField("课程名", choices=course_choices, max_length=64, blank=True, null=True, default='N/A')
    class_type = models.CharField("班级类型", choices=class_type_choices, max_length=64, blank=True, null=True,
                                  default='N/A')
    enrolment_class = models.ForeignKey('ClassList', verbose_name='所报班级', blank=True, null=True)
    customer = models.ForeignKey('Customer', verbose_name="客户")
    consultant = models.ForeignKey('UserProfile', verbose_name="销售")
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)

    status_choices = (
        (1, '未审核'),
        (2, '已审核'),
    )
    status = models.IntegerField(verbose_name='审核', default=1, choices=status_choices)

    confirm_date = models.DateTimeField(verbose_name="确认日期", null=True, blank=True)
    confirm_user = models.ForeignKey(verbose_name="确认人", to='UserProfile', related_name='confirms', null=True,
                                     blank=True)


class CourseRecord(models.Model):
    """课程记录表"""
    day_num = models.IntegerField("节次", help_text="此处填写第几节课或第几天课程...,必须为数字")
    date = models.DateField(auto_now_add=True, verbose_name="上课日期")
    course_title = models.CharField('本节课程标题', max_length=64, blank=True, null=True)
    course_memo = models.TextField('本节课程内容', max_length=300, blank=True, null=True)
    has_homework = models.BooleanField(default=True, verbose_name="本节有作业")
    homework_title = models.CharField('本节作业标题', max_length=64, blank=True, null=True)
    homework_memo = models.TextField('作业描述', max_length=500, blank=True, null=True)
    scoring_point = models.TextField('得分点', max_length=300, blank=True, null=True)
    re_class = models.ForeignKey('ClassList', verbose_name="班级")
    teacher = models.ForeignKey('UserProfile', related_name='t_course_record', verbose_name="讲师")
    recorder = models.ForeignKey('UserProfile', related_name='r_course_record', verbose_name="记录者")

    class Meta:
        unique_together = ('re_class', 'day_num')

    def __str__(self):
        return '{}-day{}'.format(self.re_class,self.day_num)


class StudyRecord(models.Model):
    """
    学习记录
    """

    attendance = models.CharField("考勤", choices=attendance_choices, default="checked", max_length=64)
    score = models.IntegerField("本节成绩", choices=score_choices, default=-1)

Day76/first_crm/crm/views/teacher.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from django.shortcuts import render, redirect, reverse
from django.http.response import JsonResponse
from crm.forms import ClassForm, CourseRecordForm,StudyRecordForm
from crm import models
from comm.pagination import Pagination
from django.views import View
from django.forms import modelformset_factory
import json


def class_list(request):
    page = request.GET.get('page', 1)
    obj_list = models.ClassList.objects.all()
    pagination = Pagination(page, obj_list.count())
    return render(request, 'teacher/class_list.html',
                  {'obj_list': obj_list[pagination.start:pagination.end], 'page_list': pagination.page_html})


class OperClass(View):
    def get(self, request, pk=None, *args, **kwargs):
        class_obj = models.ClassList.objects.filter(pk=pk).first()
        form_obj = ClassForm(instance=class_obj)
        title = '编辑信息' if pk else '添加信息'
        return render(request, 'teacher/oper_class.html', {'form_obj': form_obj, 'title': title})

    def post(self, request, pk=None, *args, **kwargs):
        class_obj = models.ClassList.objects.filter(pk=pk).first()
        form_obj = ClassForm(data=request.POST, instance=class_obj)
        if form_obj.is_valid():
            form_obj.save()
            return redirect('class')
        title = '编辑信息' if pk else '添加信息'
        return render(request, 'teacher/oper_class.html', {'form_obj': form_obj, 'title': title})


def course_record_list(request, class_pk):
    page = request.GET.get('page', 1)
    obj_list = models.CourseRecord.objects.filter(re_class_id=class_pk).order_by('-pk')
    pagination = Pagination(page, obj_list.count())
    request.session['return_url'] = request.get_full_path()
    return render(request, 'teacher/course_record_list.html',
                      {'obj_list': obj_list[pagination.start:pagination.end], 'page_list': pagination.page_html,
                       'class_pk': class_pk})


def oper_course_record(request, pk=None, class_pk=None):
    course_record = models.CourseRecord(re_class_id=class_pk,
                                        recorder=request.user_obj) if class_pk else models.CourseRecord.objects.filter(
        pk=pk).first()
    form_obj = CourseRecordForm(instance=course_record)
    if request.method == 'POST':
        form_obj = CourseRecordForm(data=request.POST, instance=course_record)
        return_url = request.session.get('return_url')
        if form_obj.is_valid():
            form_obj.save()
            return redirect(return_url)
    title = '编辑信息' if pk else '添加信息'
    return render(request, 'teacher/oper_course_record.html', {'form_obj': form_obj, 'title': title})


def add_study_record(request):
    pk_list = json.loads(request.POST.get('pk_list'))
    course_records = models.CourseRecord.objects.filter(pk__in=pk_list)
    for course_record in course_records:
        enrollments = course_record.re_class.enrollment_set.filter(customer__status='studying')
        student_list = []
        for enrollment in enrollments:
            student_list.append(models.StudyRecord(course_record=course_record,student=enrollment.customer))
        models.StudyRecord.objects.bulk_create(student_list)
    return JsonResponse({'info':'添加成功'})


def study_record_list(request,course_pk):
    ModelFormSet = modelformset_factory(models.StudyRecord,StudyRecordForm,extra=0)
    formset_obj = ModelFormSet(queryset=models.StudyRecord.objects.filter(course_record_id=course_pk))
    if request.method == 'POST':
        formset_obj = ModelFormSet(queryset=models.StudyRecord.objects.filter(course_record_id=course_pk),data=request.POST)
        return_url = request.session.get('return_url')
        if formset_obj.is_valid():
            formset_obj.save()
            if return_url:
                return redirect(return_url)

    return render(request,'teacher/study_record_list.html',{'form_set_obj':formset_obj})

Day76/first_crm/crm/templates/consultant/consult_record_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="panel panel-info">
        <div class="panel-heading" style="font-size: 18px">跟进信息</div>
        <div class="panel-body">
            <button id="view" class="btn btn-info" type="button">查看<span class="glyphicon glyphicon-search"
                                                                         aria-hidden="true"></span></button>
            <a href="{% url 'add_consult_record' customer_pk %}" class="btn btn-info">新增<span class="glyphicon glyphicon-plus"
                                                                                  aria-hidden="true"></span></a>
            <a id="edit" href="javascript:void(0);" class="btn btn-info">编辑<span class="glyphicon glyphicon-pencil"
                                                                                 aria-hidden="true"></span></a>

            <form action="" class="form-inline pull-right">
                <input class="form-control" type="text" name="query" placeholder="搜索">
                <button class="btn btn-info">搜索</button>
            </form>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>序号</th>
                    <th>ID</th>
                    <th>客户</th>
                    <th>跟进描述</th>
                    <th>跟进状态</th>
                    <th>跟进人</th>
                    <th>跟进日期</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in obj_list %}
                    <tr data-pk="{{ obj.pk }}">
                        <td>{{ forloop.counter }}</td>
                        <td>{{ obj.pk }}</td>
                        <td>{{ obj.customer }}</td>
                        <td>{{ obj.note|truncatechars:25 }}</td>
                        <td>{{ obj.get_status_display }}</td>
                        <td>{{ obj.consultant }}</td>
                        <td>{{ obj.date }}</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
            <div class="">
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        {% for page in page_list %}
                            {{ page|safe }}
                        {% endfor %}

                    </ul>
                </nav>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">

            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script>
        $(function () {
            $('tbody tr').click(function () {
                $(this).addClass('info');
                $(this).siblings().removeClass('info');
            });
            $('#edit').click(function () {
                obj = $('tr[class="info"]');
                if (obj.length === 0) {
                    swal({
                        title: "提示",
                        text: "请选择一条数据!",
                        icon: "info",
                        button: "确定",
                    });
                } else {
                    window.location = '/crm/edit_consult_record/' + obj.attr('data-pk') + '/';
                }
            });
            $('#view').click(function () {
                obj = $('tr[class="info"]');
                if (obj.length === 0) {
                    swal({
                        title: "提示",
                        text: "请选择一条数据!",
                        icon: "info",
                        button: "确定",
                    });
                } else {
                    $('#myModal').modal({
                        remote: '/crm/details/' + obj.attr('data-pk') + '/ConsultRecord/ConsultRecordForm/',
                    });
                }
            });
            $("#myModal").on("hidden.bs.modal", function () {
                $(this).removeData("bs.modal");
            });
        });
    </script>
{% endblock %}

Day76/first_crm/crm/templates/consultant/customer_list.html
{% extends 'layout.html' %}
{% load static %}
{% block css %}
    <style>
        span {
            margin-left: 5px;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="panel panel-info">
        <div class="panel-heading" style="font-size: 18px">客户信息</div>
        <div class="panel-body">
            <button id="view" class="btn btn-info" type="button">查看<span class="glyphicon glyphicon-search"
                                                                         aria-hidden="true"></span></button>
            <a href="{% url 'add_customer' %}" class="btn btn-info">新增<span class="glyphicon glyphicon-plus"
                                                                            aria-hidden="true"></span></a>
            <a id="edit" href="javascript:void(0);" class="btn btn-info">编辑<span class="glyphicon glyphicon-pencil"
                                                                                 aria-hidden="true"></span></a>
            <button id="change" class="btn btn-info" data-type="{{ type }}">
                {% if type %}
                    私户转公户
                {% else %}
                    公户转私户
                {% endif %}
                <span class="glyphicon glyphicon-refresh"
                      aria-hidden="true"></span>
            </button>
            {% if type %}
                <a id="record" href="javascript:void(0);" class="btn btn-info">跟进记录<span
                        class="glyphicon glyphicon-pencil"
                        aria-hidden="true"></span></a>
            {% endif %}
            {% if type %}
                <a id="enrollment" href="javascript:void(0);" class="btn btn-info">添加报名信息</a>
            {% endif %}
            <form action="" class="form-inline pull-right">
                <input class="form-control" type="text" name="query" placeholder="搜索">
                <button class="btn btn-info">搜索</button>
            </form>

            <form action="javascript:void(0)" method="post">
                {% csrf_token %}
                <table class="table table-striped table-hover">
                    <thead>
                    <tr>
                        <th>选择</th>
                        <th>序号</th>
                        <th>ID</th>
                        <th>姓名</th>
                        <th>性别</th>
                        <th>QQ</th>
                        <th>手机号</th>
                        <th>咨询课程</th>
                        <th>班级类型</th>
                        <th>状态</th>
                        <th>最后跟进时间</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for customer in customer_list %}
                        <tr data-pk="{{ customer.pk }}">
                            <td>
                                <input type="checkbox" name="pk" value="{{ customer.pk }}">
                            </td>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ customer.pk }}</td>
                            <td>{{ customer.name }}</td>
                            <td>{{ customer.get_sex_display }}</td>
                            <td>{{ customer.qq }}</td>
                            <td>{{ customer.phone|default:'-' }}</td>
                            <td>{{ customer.course }}</td>
                            <td>{{ customer.get_class_type_display }}</td>
                            <td>{{ customer.get_status }}</td>
                            <td>{{ customer.last_consult_date }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </form>
            <div class="">
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        {% for page in page_list %}
                            {{ page|safe }}
                        {% endfor %}

                    </ul>
                </nav>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">

            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script>
        $(function () {
            $('tbody tr').click(function () {
                $(this).addClass('info');
                $(this).siblings().removeClass('info');
            });
            $('#edit').click(function () {
                obj = $('tr[class="info"]');
                if (obj.length === 0) {
                    swal({
                        title: "提示",
                        text: "请选择一条数据!",
                        icon: "info",
                        button: "确定",
                    });
                } else {
                    window.location = '/crm/edit_customer/' + obj.attr('data-pk') + '/';
                }
            });
            $('#view').click(function () {
                obj = $('tr[class="info"]');
                if (obj.length === 0) {
                    swal({
                        title: "提示",
                        text: "请选择一条数据!",
                        icon: "info",
                        button: "确定",
                    });
                } else {
                    $('#myModal').modal({
                        remote: '/crm/details/' + obj.attr('data-pk') + '/Customer/CustomerForm/',
                    });
                }
            });

            $("#myModal").on("hidden.bs.modal", function () {
                $(this).removeData("bs.modal");
            });

            $('#enrollment').click(function () {
                obj = $('tr[class="info"]');
                if (obj.length === 0) {
                    swal({
                        title: "提示",
                        text: "请选择一条数据!",
                        icon: "info",
                        button: "确定",
                    });
                } else {

                    location = '/crm/add_enrollment/' + obj.attr('data-pk') + '/';

                }
            });

            $('#record').click(function () {
                obj = $('tr[class="info"]');
                if (obj.length === 0) {
                    swal({
                        title: "提示",
                        text: "请选择一条数据!",
                        icon: "info",
                        button: "确定",
                    });
                } else {

                    location = '/crm/cus_consult_record_list/' + obj.attr('data-pk') + '/';

                }
            });

            $('#change').click(function () {
                obj = $('input[name="pk"]').filter(function () {
                    return $(this).prop('checked') === true
                });
                if (obj.length === 0) {
                    swal({
                        title: "提示",
                        text: "请至少选择一条数据!",
                        icon: "info",
                        button: "确定",
                    });
                } else {
                    var radio = document.getElementsByName('pk');
                    var pk_list = new Array();
                    //将所有选中复选框的默认值写入到id数组中
                    for (var i = 0; i < radio.length; i++) {
                        if (radio[i].checked) {
                            pk_list.push(radio[i].value);
                        }
                    }
                    $.ajax({
                        url: '/crm/customer_change/',
                        type: 'post',
                        data: {
                            csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]').val(),
                            pk_list: JSON.stringify(pk_list),
                            type: $('#change').attr('data-type'),
                        },
                        success: function (res) {
                            swal({
                                title: "提示",
                                text: res.info,
                                icon: "info",
                                button: "确定",
                            }).then(() => {
                                location = res.url;
                            });


                        }
                    })
                }
            })
        });


    </script>
{% endblock %}

Day76/first_crm/crm/templates/consultant/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title" id="myModalLabel">详细信息</h4>
</div>
<div class="modal-body">
    <form action="" method="post" class="form-horizontal" novalidate>
        <fieldset disabled>
            {% for field in form_obj %}
                <div class="form-group {% if field.errors %}has-error{% endif %}">
                    <label for="{{ field.id_for_label }}"
                           class="col-md-3 control-label">{{ field.label }}</label>
                    <div class="col-md-7">{{ field }}</div>
                </div>
            {% endfor %}
        </fieldset>
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">确定</button>
</div>
</body>
</html>

Day76/first_crm/crm/templates/consultant/oper_consult_record.html
{% extends 'layout.html' %}
{% block content %}
    <div class="panel panel-info">
        <div class="panel-heading" style="font-size: 18px">{{ title }}</div>
        <div class="panel-body">
            <div class="col-md-8 col-md-offset-2">
                <form action="" class="form-horizontal" method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form_obj %}
                        <div class="form-group {% if field.errors %}has-error{% endif %}">
                            <label for="{{ field.id_for_label }}"
                                   style="{% if not field.field.required %}color: #999{% endif %}"
                                   class="col-md-3 control-label">{{ field.label }}</label>
                            <div class="col-md-7">{{ field }}</div>
                            <span class="help-block">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}
                    <button class="btn btn-info col-md-1 col-md-offset-9">保存</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}