Day60/bookmanage/appBook/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from django.conf.urls import url
from appBook import views

urlpatterns = [
    url(r'^book_list/$', views.BookList.as_view(),name='book'),
    url(r'^add_book/$', views.AddBook.as_view(),name='add'),
    url(r'^edit_book/$', views.EditBook.as_view(),name='edit'),
]

Day60/bookmanage/appPublic/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from django.conf.urls import url
from appPublic import views

urlpatterns = [
    url(r'^del_(book|author|publisher)/(\d+)$', views.delete,name='del'),
]

Day60/bookmanage/bookmanage/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from appPublic import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^apppublisher/', include('appPublisher.urls',namespace='appPublisher')),
    url(r'^appbook/', include('appBook.urls',namespace='appBook')),
    url(r'^appauthor/', include('appAuthor.urls',namespace='appAuthor')),
    url(r'^apppublic/', include('appPublic.urls',namespace='appPublic')),


    url(r'^$', views.index),
]

Day60/bookmanage/templates/book/add_book.html
{% extends 'base.html' %}

{% block content %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <h3 style="margin-bottom: 18px">
                    添加数据
                </h3>
            </div>
        </div>

    </section>

    <!-- Main content -->
    <section class="container-fluid">

        <!--------------------------
          | Your Page Content Here |
          -------------------------->
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <!-- Horizontal Form -->
                <div class="box box-info">
                    <div class="box-header with-border">
                        <h3 class="box-title">图书信息</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form class="form-horizontal" method="post" action="">
                        <div class="box-body">
                            <div class="form-group">
                                <label for="inputName" class="col-sm-3 control-label">图书名称</label>

                                <div class="col-sm-9">
                                    <input type="text" class="form-control" name="book_name" id="inputName"
                                           placeholder="请输入图书名称">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">出版社名称</label>
                                <div class="col-sm-9">
                                    <select class="form-control" name="publisher">
                                        {% for publisher in publisher_list %}
                                            <option value="{{ publisher.pk }}">{{ publisher.name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>

                            <div style="color: red">{{ error }}</div>
                        </div>
                        <!-- /.box-body -->
                        <div class="box-footer">
                            <button type="button" class="btn btn-default">重置</button>
                            <button type="submit" class="btn btn-info pull-right">添加</button>
                        </div>
                        <!-- /.box-footer -->
                    </form>
                </div>
                <!-- /.box -->
            </div>
        </div>

    </section>
    <!-- /.content -->
{% endblock %}

{% block js %}
    <script>
        $(function () {
            $('button[type=button]').click(function () {
                $('#inputName').val('');
            })
        })
    </script>
{% endblock %}

Day60/bookmanage/templates/book/book_list.html
{% extends 'base.html' %}

{% block content %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1 style="margin-bottom: 15px">
            数据查询
        </h1>
        <div class="row" style="margin-bottom: 14px">
            <div class="col-lg-1" style="font-size: 12px;">
                <a href="{% url 'appBook:add' %}" class="btn btn-success btn-sm">
                    <span style="padding-right: 3px">添加</span>
                    <i class="iconfont">&#xe602;</i>
                </a>
            </div>
        </div>
    </section>

    <!-- Main content -->
    <section class="container-fluid">

        <!--------------------------
          | Your Page Content Here |
          -------------------------->
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">图书信息</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th width="8%">序号</th>
                                <th width="8%">ID</th>
                                <th width="36%">名称</th>
                                <th width="36%">出版社</th>
                                <th width="12%">操作</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for book in book_list %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ book.bid }}</td>
                                    <td>{{ book.name }}</td>
                                    <td>{{ book.pub.name }}</td>
                                    <td>
                                        <a href="{% url 'appBook:edit' %}?bid={{ book.bid }}">
                                            <i class="iconfont"
                                               style="margin-left:18px;margin-right: 8px">&#xe601;</i>
                                        </a>
                                        <span>|</span>
                                        <a href="{% url 'appPublic:del' 'book' book.bid %}" style="margin-left: 8px;">
                                            <i class="iconfont">&#xe600;</i>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
            </div>
        </div>
    </section>
    <!-- /.content -->
{% endblock %}

Day60/bookmanage/templates/book/edit_book.html
{% extends 'base.html' %}

{% block content %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <h3 style="margin-bottom: 18px">
                    编辑数据
                </h3>
            </div>
        </div>

    </section>

    <!-- Main content -->
    <section class="container-fluid">

        <!--------------------------
          | Your Page Content Here |
          -------------------------->
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <!-- Horizontal Form -->
                <div class="box box-info">
                    <div class="box-header with-border">
                        <h3 class="box-title">图书信息</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form class="form-horizontal" method="post" action="">
                        <div class="box-body">
                            <div class="form-group">
                                <label for="inputName" class="col-sm-3 control-label">图书名称</label>

                                <div class="col-sm-9">
                                    <input type="text" class="form-control" name="book_name" id="inputName"
                                           placeholder="请输入图书名称" value="{{ book.name }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">出版社名称</label>
                                <div class="col-sm-9">
                                    <select class="form-control" name="publisher">
                                        {% for publisher in publisher_list %}
                                            {% if book.pub == publisher %}
                                                <option selected
                                                        value="{{ publisher.pk }}">{{ publisher.name }}</option>
                                            {% else %}
                                                <option value="{{ publisher.pk }}">{{ publisher.name }}</option>
                                            {% endif %}

                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <div style="color: red">{{ error }}</div>
                        </div>
                        <!-- /.box-body -->
                        <div class="box-footer">
                            <button type="button" class="btn btn-default">重置</button>
                            <button type="submit" class="btn btn-info pull-right">保存</button>
                        </div>
                        <!-- /.box-footer -->
                    </form>
                </div>
                <!-- /.box -->
            </div>
        </div>

    </section>
    <!-- /.content -->
{% endblock %}

{% block js %}
    <script>
        $(function () {
            $('button[type=button]').click(function () {
                $('#inputName').val('');
            })
        })
    </script>
{% endblock %}